#!/usr/bin/env bash

set -eu

# get the name of the repo on the remote
REPO=$(git remote get-url origin | awk '{split($1,a,"/"); print(a[2])}')

# echo $TEMP

if ! [[ $(git remote) == *origin_gh* ]]
then
    echo "Adding github remote 'git@github.com:noxthot/ss22_julia_workshop.git'"
    git remote add origin_gh "git@github.com:noxthot/ss22_julia_workshop.git"
fi

echo "Installing git pu alias" 
git config alias.pu '!sh -c "$(git rev-parse --show-toplevel)/.gitconfigs/push"'
echo "Done!"
